version: "3.9"
services:
  application:
    image: humbertobonadiman/clinica-veterinaria-spring_application
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3308/clinica_veterinaria_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.generate-ddl": "true",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.servlet.multipart.max-file-size": "10MB",
        "spring.servlet.multipart.max-request-size": "10MB",
        "spring.servlet.multipart.enabled" : "true"
      }'
    networks:
      - clinica-veterinaria-net
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - clinica-veterinaria-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=clinica_db
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_HOST='%'
      - MYSQL_TCP_PORT=3308
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    ports:
      - 3308:3308
    expose:
      - 3308
networks:
  clinica-veterinaria-net:
     driver: bridge
volumes:
  db:
